from textwrap import dedent
from crewai import Task


class TasksStack:
	@staticmethod
	def research_task(agent, app_idea):
		return Task(
			description=dedent(f"""\
        Conduct comprehensive research on each of necessary components
				involved in the development of the app. Gather information on best tools, up-to-date information, 
				industry standards, libraries, patterns and principles necessary to develop the app.

				App to develop: {app_idea}
				"""),
			expected_output=dedent(f"""\
        A detailed report summarizing key findings about each component, highlighting information that could be relevant for development."""),
			agent=agent,
			async_execution=True
		)

	@staticmethod
	def design_task(agent, app_idea):
		return Task(
			description=dedent(f"""\ Design the general structure of the software, the key parts and components that 
			are going to be implemented by the developers, separate the sub-tasks into frontend and backend tasks App 
			to develop: {app_idea}
"""),
			expected_output=dedent("""\
				Every necessary component of the application, separated in frontend and backend."""),
			agent=agent
		)

	@staticmethod
	def develop_backend_task(agent, app_idea):
		return Task(
			description=dedent(f"""\
				Develop the backend of the application
				App to develop: {app_idea}"""),
			expected_output=dedent("""\
				Generate all the backend files necessary for the application's backend to be work and be used by the frontend developer."""),
			agent=agent
		)

	@staticmethod
	def develop_frontend_task(agent, app_idea):
		return Task(
			description=dedent(f"""Develop the frontend of the application"""),
			expected_output=dedent(f"""\
				Generate all the frontend files necessary for the application to be work using the code generated by the backend developer.
				App to develop: {app_idea}"""),
			agent=agent
		)

	@staticmethod
	def qa_task(agent, app_idea):
		return Task(
			description=dedent(f"""\
				Check the code generated by frontend and backend and ensure that it is to the best quality and without bugs.

				App to develop: {app_idea}"""),
			expected_output=dedent("""\
				A well structured report on possible and existing bugs."""),
			agent=agent
		)

	@staticmethod
	def writing_code_task(agent, app_idea):
		return Task(
			description=f"""
			Summarize and organize all the necessary code files generated by the team members.

			App to develop: {app_idea}
			""",
			expected_output=f"""
			Create a folder structure with the files containing each one of them.
			""",
			agent=agent
		)
